### ISSUE TITLE
Empty folders when using Tool

### ISSUE THREAD

**Issue by matanporeh** [Cocoanetics/POEditorAPI#6] opened 2016-11-20 10:30 UTC
used the tool to import translations from POEditor and all folders created were empty without any error messages

**Comment by odrobnik** [comment] 2016-11-26 11:27
I am at present relying on the context being set which it is if you import XLIFF into POEditor - as recommended by Apple. 

Previously I had it such that I would automatically assume the context to be `Localizable.strings` if there was no context, but that caused problems when there were actually also tokens that had this in the context.

I don't know yet how to best address this in a smart way.

**Comment by odrobnik** [comment] 2016-12-17 15:58
The root cause for this issue was that the file extension was wrong - which you fixed in your pull request that I rejected. But you also modified the output path which is used for manual export.

This way you can have both, either you just run `poet` and get the lproj structure updated, or if you run `poet apple_strings` you get `en.strings` written to the output folder.

There is no good reason not to use the automatic mode (without parameters).

**Closed as completed** 2016-12-17 15:59 UTC
Labels: bug
